2021-06-27 00:52:33,696 INFO    Thread-2  :98332 [wandb_setup.py:_flush():69] setting env: {'project': 'MLN_sweep_mnist_symmetric_0.2', 'entity': 'jeongeun', 'root_dir': '/home/jeongeun/MLN_XRobust', 'sweep_id': 'ide52c97', 'run_id': '2zg7a31c', 'sweep_param_path': '/home/jeongeun/MLN_XRobust/wandb/sweep-ide52c97/config-2zg7a31c.yaml'}
2021-06-27 00:52:33,696 INFO    Thread-2  :98332 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-27 00:52:33,696 INFO    Thread-2  :98332 [wandb_init.py:_log_setup():337] Logging user logs to /home/jeongeun/MLN_XRobust/wandb/run-20210627_005233-2zg7a31c/logs/debug.log
2021-06-27 00:52:33,696 INFO    Thread-2  :98332 [wandb_init.py:_log_setup():338] Logging internal logs to /home/jeongeun/MLN_XRobust/wandb/run-20210627_005233-2zg7a31c/logs/debug-internal.log
2021-06-27 00:52:33,697 INFO    Thread-2  :98332 [wandb_init.py:init():370] calling init triggers
2021-06-27 00:52:33,697 INFO    Thread-2  :98332 [wandb_init.py:init():375] wandb.init called with sweep_config: {'ratio1': 10, 'ratio2': 10}
config: {'k': 5, 'sig_min': 1, 'sig_max': 10, 'lr': 0.001, 'wd': 5e-06, 'lr_rate': 0.5}
2021-06-27 00:52:33,697 INFO    Thread-2  :98332 [wandb_init.py:init():419] starting backend
2021-06-27 00:52:33,697 INFO    Thread-2  :98332 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-27 00:52:33,729 INFO    Thread-2  :98332 [backend.py:ensure_launched():135] starting backend process...
2021-06-27 00:52:33,755 INFO    Thread-2  :98332 [backend.py:ensure_launched():139] started backend process with pid: 98471
2021-06-27 00:52:33,757 INFO    Thread-2  :98332 [wandb_init.py:init():424] backend started and connected
2021-06-27 00:52:33,759 INFO    Thread-2  :98332 [wandb_run.py:_config_callback():873] config_cb None None {'ratio1': 10, 'ratio2': 10}
2021-06-27 00:52:33,760 INFO    Thread-2  :98332 [wandb_init.py:init():472] updated telemetry
2021-06-27 00:52:33,761 INFO    Thread-2  :98332 [wandb_init.py:init():491] communicating current version
2021-06-27 00:52:34,538 INFO    Thread-2  :98332 [wandb_init.py:init():496] got version response 
2021-06-27 00:52:34,538 INFO    Thread-2  :98332 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-06-27 00:52:34,547 ERROR   Thread-2  :98332 [wandb_init.py:init():783] error
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 757, in init
    run = wi.init()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 505, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 666, in communicate_run
    run = self._make_run(run_obj)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 240, in _make_run
    run._make_proto_run(proto_run)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 449, in _make_proto_run
    run.display_name = self._name
TypeError: 1 has type int, but expected one of: bytes, unicode
2021-06-27 00:52:36,553 ERROR   MainThread:98332 [pyagent.py:_run_jobs_from_queue():231] Run 2zg7a31c errored: Exception('problem')
