2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_setup.py:_flush():69] setting env: {'project': 'MLN_sweep_cifar10_symmetric_0.8', 'entity': 'jeongeun', 'root_dir': '/home/jeongeun/MLN_XRobust', 'run_id': 'hvh1krtf', 'sweep_param_path': '/home/jeongeun/MLN_XRobust/wandb/sweep-64frun38/config-hvh1krtf.yaml', 'sweep_id': '64frun38'}
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_init.py:_log_setup():337] Logging user logs to /home/jeongeun/MLN_XRobust/wandb/run-20210701_092150-hvh1krtf/logs/debug.log
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_init.py:_log_setup():338] Logging internal logs to /home/jeongeun/MLN_XRobust/wandb/run-20210701_092150-hvh1krtf/logs/debug-internal.log
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_init.py:init():370] calling init triggers
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_init.py:init():375] wandb.init called with sweep_config: {'ratio1': 1, 'ratio2': 2}
config: {'k': 24, 'sig_min': 1, 'sig_max': 10, 'lr': 5e-05, 'wd': 0.0005, 'lr_rate': 0.5}
2021-07-01 09:21:50,334 INFO    Thread-42 :25220 [wandb_init.py:init():419] starting backend
2021-07-01 09:21:50,335 INFO    Thread-42 :25220 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-01 09:21:50,337 INFO    Thread-42 :25220 [backend.py:ensure_launched():135] starting backend process...
2021-07-01 09:21:50,394 INFO    Thread-42 :25220 [backend.py:ensure_launched():139] started backend process with pid: 103509
2021-07-01 09:21:50,395 INFO    Thread-42 :25220 [wandb_init.py:init():424] backend started and connected
2021-07-01 09:21:50,397 INFO    Thread-42 :25220 [wandb_run.py:_config_callback():873] config_cb None None {'ratio1': 1, 'ratio2': 2}
2021-07-01 09:21:50,398 INFO    Thread-42 :25220 [wandb_init.py:init():472] updated telemetry
2021-07-01 09:21:50,399 INFO    Thread-42 :25220 [wandb_init.py:init():491] communicating current version
2021-07-01 09:21:51,226 INFO    Thread-42 :25220 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-07-01 09:21:51,227 INFO    Thread-42 :25220 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-01 09:21:51,443 INFO    Thread-42 :25220 [wandb_init.py:init():529] starting run threads in backend
2021-07-01 09:21:51,511 INFO    Thread-42 :25220 [wandb_run.py:_console_start():1624] atexit reg
2021-07-01 09:21:51,512 INFO    Thread-42 :25220 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.REDIRECT
2021-07-01 09:21:51,512 INFO    Thread-42 :25220 [wandb_run.py:_redirect():1503] Redirecting console.
2021-07-01 09:21:51,512 ERROR   Thread-42 :25220 [wandb_run.py:_redirect():1562] Failed to redirect.
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1555, in _redirect
    out_redir.install()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/jeongeun/.pyenv/versions/3.8.8/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-07-01 09:21:51,512 INFO    Thread-42 :25220 [wandb_init.py:init():554] run started, returning control to user process
2021-07-01 09:21:51,512 INFO    Thread-42 :25220 [wandb_watch.py:watch():40] Watching
2021-07-01 09:56:14,246 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:14,246 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"errors":[{"message":"Error 1040: Too many connections","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2021-07-01 09:56:20,180 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:20,181 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"error":"Error 1040: Too many connections"}

2021-07-01 09:56:24,735 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:24,735 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"errors":[{"message":"Error 1040: Too many connections","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2021-07-01 09:56:24,736 ERROR   Thread-1  :25220 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2021-07-01 09:56:30,021 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:30,021 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"errors":[{"message":"Error 1040: Too many connections","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2021-07-01 09:56:38,739 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:38,739 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"error":"Error 1040: Too many connections"}

2021-07-01 09:56:56,992 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:56:56,993 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"error":"Error 1040: Too many connections"}

2021-07-01 09:57:32,457 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:57:32,458 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"error":"Error 1040: Too many connections"}

2021-07-01 09:58:49,271 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 500 response executing GraphQL.
2021-07-01 09:58:49,272 ERROR   Thread-1  :25220 [internal_api.py:execute():131] {"error":"Error 1040: Too many connections"}

2021-07-01 10:01:16,258 ERROR   Thread-1  :25220 [internal_api.py:execute():130] 502 response executing GraphQL.
2021-07-01 10:01:16,259 ERROR   Thread-1  :25220 [internal_api.py:execute():131] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2021-07-01 12:08:16,582 INFO    Thread-42 :25220 [wandb_run.py:finish():1294] finishing run jeongeun/MLN_sweep_cifar10_symmetric_0.8/hvh1krtf
